### ISSUE TITLE
RFC_SERIALIZATION_FAILURE in case of nested input structures

### ISSUE THREAD

**Issue by softy12** [SAP/node-rfc#53] opened 2018-05-31 13:40 UTC
Hi,

I have a custom BAPI that serves as an interface for a call of standard SAP object (method) cmd_ei_api=>maintain_bapi. The maintain_bapi method has an input parameter IS_MASTER_DATA TYPE CMDS_EI_MAIN. The type is very deep one with many levels of nested structures. When I call my custom BAPI from nodejs app I'm experiencing performance issue (it takes 7 minutes to execute in contrast to few seconds when I run the same BAPI via SAP GUI) and also sometimes an error RC12 RFC_SERIALIZATION_FAILURE occurs. 
What can be done to solve RFC_SERIALIZATION_FAILURE error and performance issue?

thanks

**Comment by bsrdjan** [comment] 2018-06-08 09:05
Deep nested structures, like CMDS_EI_MAIN, are indeed a performance challenge for current SAP NW RFC SDK design, especially over slower networks. 

Following might help a bit:

* Using the latest SAP NW RFC SDK

* Using node-rfc `napi` branch

* Check if [basXML](https://help.sap.com/saphelp_nwpi711/helpdata/en/48/9bde7a0c1c73e7e10000000a42189b/frameset.htm) option available in backend system and mark the BAPI as basXML.

* "Flattening" this deep nested structure in a custom BAPI, if not too much efforts/complicated? 

Regarding 7 minutes runtime, are nodejs and ABAP server close in terms of network topology and how much data records approx. are transferred? I see this deep nested structure is input parameter. Is a bigger data volume sent from nodejs to ABAP, or from ABAP to nodejs? Or the bigger data transfer goes in both directions?

**Comment by softy12** [comment] 2018-06-13 16:51
Hi Srdjan,

thanks for your reply!
- I'm using the latest version of the. Using the latest SAP NW RFC SDK. I also set basXML flag on my function module.
- I haven't tried "napi branch" feature yet.
The only thing that rWhat really helped me was to flatten structures. In case I do not use nested structures at all then the runtime of my function module.

To your questions:
- geo proximity - Client and SAP backend are not close in terms of network topology (EU vs Asia)
- amount of data transferred - Can't judge whether the bigger portion of data is sent from nodejs to ABAP or other way around. I'm sending just values for few fields on input. Also, the values of few fields are returned. However, even the values of fields are not present the whole structures with its fields are returned. So perhaps that is the issue? Is it really needed to send out all parameters even they do not have any values?

thanks

**Comment by bsrdjan** [comment] 2018-06-15 09:02
Hi,

hm, few fields should actually not be a problem. 

Not returning certain parameters is supported in napi branch and works like in [unit test](https://github.com/SAP/node-rfc/blob/napi/test/options.js#L36). The feature is provided for RFC modules with "IF REQUESTED" ABAP logic, like in unit test, or to avoid transferring bigger output parameters, when not needed in nodejs application. The list of parameters to "skip", must be provided when making RFC call. The connector itself can't figure out if the structure is empty because a zero value for example could mean "no value" or value zero. The parameters' list must be therefore provided by consumer but in this particular case would not help much, I expect.

Nevertheless, I would like to have a look in your system, if possible? 

In parallel, I am looking for SAP internal system, to try to reproduce.

Regards,.
Srdjan

**Comment by bsrdjan** [comment] 2018-06-22 06:57
Following our Email conversation and further testing, the RFC_SERIALIZATION_FAILURE is caused by sending the wrong function module parameter name from nodejs app. The correct error to be thrown  in this case is RFC_INVALID_PARAMETER and that is how the @next release behaves. I used that version in my test and that is why my result was different. 

Regarding performance issue, I will investigate in internal test system, if inbound processing eventually enough to reproduce, because with your test input data most likely no results will be returned in my system.

**Comment by bsrdjan** [comment] 2018-06-25 13:52
Could you please post the ABAP FM source and the JS test script source, that I could replicate and test?

**Comment by bsrdjan** [comment] 2018-06-29 09:07
Performance issue is reproduced with this simple FM:

```abap
FUNCTION ZNESTED.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IS_MASTER_DATE) TYPE  CMDS_EI_MAIN
*"----------------------------------------------------------------------
" empty
ENDFUNCTION.
```
end test script:

```javascript
(async () => {
	try {
		console.time('client.open');
		await client.open();
		console.timeEnd('client.open');

		console.time('client.call');
		let res = await client.call('ZNESTED', {});
		console.timeEnd('client.call');
	} catch (ex) {
		console.error(ex);
	}
})();
```

Could you please post the output of the above script, calling your system? You could implement ZNESTED function module, or simply call your function module (replace `client.call('ZNESTED' ...` with your call). 

Could you please check if your ABAP system is perhaps an S4 system, in which the class CL_MD_BP_MAINTAIN is available and if using that class could be an option in your case?

**Comment by bsrdjan** [comment] 2018-07-06 13:33
After further investigation in internal systems, with latest service packs and corrections from [SAP oss note 1456826](https://launchpad.support.sap.com/#/notes/1456826), the recommendation is to "flatten" this hierarchical structure, by adapting ABAP remote function module logic and signature. Current metadata processing on ABAP side can't handle this particular structure any faster than experienced in your system. Sorry that no more elegant solution can be provided.

**Comment by softy12** [comment] 2018-07-16 16:13
Hi Srdjan, 

Sorry for late reply, we had some issues with connectivity to the SAP server.
I created empty FM ZNESTED as per your instruction and I tried to call FM ZNESTED from the regular version of the node-rfc [ 7500, 0, 0 ] and also from N-API version ({ major: 7500, minor: 0, patchLevel: 0, binding: '0.2.0-rc6 (node:1716)) of the same.

- in the regular node-rfc version a call of the FM takes similar time as my custom BAPI - approx 6min30sec:
Start: 2018-06-29T23:58:51.143Z
Result ZNESTED: {"IS_MASTER_DATE":{"CUSTOMERS":[]}}
End: 2018-06-30T00:05:27.034Z

- in N-API version it also took a lot of time:
client.open: 6862.893ms
client.call: 416392.016ms
value if ms is 7.9 minutes

Unfortunately, my system is not S4 based system so no possibility to use the class that you mentioned.

So as you concluded only chance here is to "flatten" hierarchical structures used by the FM/BAPI.

Anyhow thanks a lot for your effort put into this issue!

**Closed** 2018-10-29 12:19 UTC
