### ISSUE TITLE
Parallel requests fail

### ISSUE THREAD

**Issue by jaulz** [SAP/node-rfc#16] opened 2016-08-15 12:30 UTC
When I try to run two function calls at the same time I get the following error:

```
{ [Error:
ERROR       program state check for conversation 69481959
TIME        Mon Aug 15 14:29:05 2016
RELEASE     721
COMPONENT   CPIC (TCP/IP) with Unicode
VERSION     3
RC          471
MODULE      r3cpic.c
LINE        6078
DETAIL      called function STSEND in state state=BUFFER_DATA2
COUNTER     1
] code: 1, key: 'RFC_COMMUNICATION_FAILURE' }
{ [Error: Invalid RFC connection handle: 50880736] code: 13, key: 'RFC_INVALID_H
ANDLE' }
```

Does that mean I need to create a new client for each function call if I want to do it in paralell?

**Comment by bsrdjan** [comment] 2016-11-22 13:27
should be fixed by v0.1.6

**Closed** 2016-11-22 13:37 UTC

**Comment by bsrdjan** [comment] 2017-06-23 08:26
yes, the connection has a state and new client shall be used, see [Parallel requests fail #46](https://github.com/SAP/PyRFC/issues/46)

**Comment by SndChance** [comment] 2019-05-17 13:38
Hey, could this error be again in the N-API Version?
Querying some tables in parallel like CRMD_LINK or CRMD_LINKPARTNERS results in the same error jaulz had.
Reverting back to the non N-API Version works fine

**Comment by bsrdjan** [comment] 2019-05-17 14:46
Unlikely. The error is typically caused by sharing the same node-rfc client instance among multiple threads. That is not supported and happens for example often in test frameworks like mocha, spanning multiple threads in background.
